name: SQLSchemaLinter
on:
  push:
    branches: LW11
jobs:
  SQLLinter:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: "actions/checkout@v3"
      - name: Start SQLSchemaLinter
        run: |
          pip install sqlfluff
          sqlfluff lint $GITHUB_WORKSPACE/DataSchema.sql --dialect oracle
