name: SQLSchemaModifiedLinter
on:
  push:
    branches: main
jobs:
  SQLLinter:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: "actions/checkout@v3"
      - name: Start SQLSchemaModifiedLinter
        run: |
          pip install sqlfluff
          sqlfluff lint $GITHUB_WORKSPACE/DataSchemaModified.sql --dialect oracle
