name: Run SQL Tests

on:
  push:
    branches:
      - main

jobs:
  run-sql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Oracle SQLPlus
      run: |
        sudo apt-get update
        sudo apt-get install alien libaio1 unixodbc
        wget https://download.oracle.com/otn_software/linux/instantclient/193000/instantclient-basiclite-linux.x64-19.3.0.0.0dbru.zip
        wget https://download.oracle.com/otn_software/linux/instantclient/193000/instantclient-sqlplus-linux.x64-19.3.0.0.0dbru.zip
        unzip instantclient-basiclite-linux.x64-19.3.0.0.0dbru.zip
        unzip instantclient-sqlplus-linux.x64-19.3.0.0.0dbru.zip
        sudo alien -i instantclient-basiclite-*.rpm
        sudo alien -i instantclient-sqlplus-*.rpm
        echo 'export LD_LIBRARY_PATH=/usr/lib/oracle/19.3/client64/lib/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}' >> ~/.bashrc
        echo 'export PATH=/usr/lib/oracle/19.3/client64/bin:$PATH' >> ~/.bashrc
        source ~/.bashrc

    - name: Run SQL code
      run: |
        export PATH=/home/runner/instantclient:$PATH
        sqlplus shkuropatova/p1P34ab#@185.235.218.67:1521/XEPDB1 @TestCases.sql
