name: Module Testing

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Oracle Instant Client
      uses: oracle/setup-instantclient@v1
      with:
        username: shkuropatova
        password: p1P34ab#
        connect-string: "@185.235.218.67:1521/XEPDB1"

    - name: Install Oracle Instant Client libraries
      run: |
        sudo apt-get install libaio1 libaio-dev libncurses5

    - name: Set up Oracle environment
      run: |
        echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/runner/instantclient" >> $GITHUB_ENV
        echo "export ORACLE_HOME=/home/runner/instantclient" >> $GITHUB_ENV
        echo "export PATH=$PATH:/home/runner/instantclient" >> $GITHUB_ENV

    - name: Install dependencies
      run: npm install

    - name: Run Module Tests
      run: |
        /home/runner/instantclient/sqlplus shkuropatova/p1P34ab#@185.235.218.67:1521/XEPDB1 @TestCases.sql
