name: Module Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Oracle Instant Client
      uses: chrislennon/action-oracle-instantclient@v1

    - name: Install SQLPlus
      run: |
        sudo apt-get install -y oracle-instantclient-basic
        sudo apt-get install -y oracle-instantclient-sqlplus

    - name: Run Module Tests
      run: |
        sqlplus ${{ secrets.LOGIN }}/${{ secrets.PASSWORD }}@//185.235.218.67:1521/XEPDB1 @TestCases.sql
