name: Module Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ORACLE_REGISTRY_USERNAME: ${{ secrets.ORACLE_REGISTRY_USERNAME }}
      ORACLE_REGISTRY_PASSWORD: ${{ secrets.ORACLE_REGISTRY_PASSWORD }}

    services:
      oracle-db:
        image: container-registry.oracle.com/database/instantclient:12.2.0.1
        env:
          DB_PASS: ${{ secrets.PASSWORD }}
        ports:
          - 1521:1521

    steps:
    - name: Authenticate with Oracle Container Registry
      run: docker login -u $ORACLE_REGISTRY_USERNAME -p $ORACLE_REGISTRY_PASSWORD container-registry.oracle.com

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Module Tests
      run: |
        sqlplus ${{ secrets.LOGIN }}/${{ secrets.PASSWORD }}@//localhost:1521/XEPDB1 @TestCases.sql
