name: Module Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Виконання SQL на віддаленому Oracle-сервері
        runs-on: ubuntu-latest
        steps:
          - name: Checkout репозиторію
            uses: actions/checkout@v2

          - name: Виконати SQL запит
            run: |
              sqlplus username/password@//185.235.218.67:1521/XEPDB1 @TestCases.sql
