name: Test Cases
on: 
  push:
    branches: master
jobs:
 TestCases:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: "actions/checkout@v3"
  - name: Compile
    run: |
      cd $GITHUB_WORKSPACE/
      export CLASSPATH="./ojdbc8.jar:./"
      javac TestCases.java
  - name: Execute
    run: |
      cd $GITHUB_WORKSPACE/
      export CLASSPATH="./ojdbc8.jar:./"
      java TestCases ${{ secrets.LOGIN }} ${{ secrets.PASSWORD }}

# sqlplus shkuropatova/p1P34ab#@185.235.218.67:1521/XEPDB1
