name: Module Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      oracle-db:
        image: store/oracle/database-instantclient:12.2.0.1
        env:
          DB_PASS: ${{ secrets.PASSWORD }}
        ports:
          - 1521:1521

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Module Tests
      run: |
        sqlplus ${{ secrets.LOGIN }}/${{ secrets.PASSWORD }}@//localhost:1521/XEPDB1 @TestCases.sql
