name: Module Testing

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Oracle Instant Client
      uses: stefanprodan/docusaurus-action-oracledb@v1
      with:
        login: shkuropatova
        password: p1P34ab#  # Замініть на ваш пароль
        host: 185.235.218.67
        port: 1521
        service: XEPDB1

    - name: Install dependencies
      run: npm install

    - name: Run Module Tests
      run: |
        sqlplus shkuropatova/p1P34ab#@185.235.218.67:1521/XEPDB1 @path/to/your/test_script.sql
