name: Test Cases

on:
  push:
    branches: main

jobs:
  TestCases:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Execute Tests
      run: |
        cd $GITHUB_WORKSPACE/
        chmod +x TestCases.sh
        ./TestCases.sh ${{ secrets.LOGIN }} ${{ secrets.PASSWORD }}
