name: Run Oracle SQL

on:
  push:
    branches:
      - main

jobs:
  run-sql:
    runs-on: ubuntu-latest

    env:
      ORACLE_USERNAME: shkuropatova
      ORACLE_PASSWORD: p1P34ab#
      ORACLE_CONNECTION_STRING: //185.235.218.67:1521/XEPDB1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Oracle Instant Client
      run: |
        sudo apt-get install -y libaio1
        mkdir -p ~/instantclient
        cd ~/instantclient
        wget https://download.oracle.com/otn_software/linux/instantclient/199000/instantclient-basic-linux.x64-19.9.0.0.0dbru.zip
        unzip instantclient-basic-linux.x64-19.9.0.0.0dbru.zip
        echo '/instantclient' | sudo tee -a /etc/ld.so.conf.d/oracle-instantclient.conf
        sudo ldconfig

    - name: Run SQL script
      run: |
        echo "exit" | sqlplus -S $ORACLE_USERNAME/$ORACLE_PASSWORD@$ORACLE_CONNECTION_STRING @path/to/your/sql/script.sql
